project:
  type: book
  output-dir: docs

book:
  title: "Programmatic Data Processing Essentials for GIS Specialists"
  author: "LADOT Commerical Rideshare & Mobility"
  date: today
  chapters:
    - index.qmd
    - installation.qmd
    - r-projects.qmd
    - intro-r-programming.qmd
    - cleaning-and-wrangling.qmd
    - hh-exercise-palmer-penguins.qmd
    # - data-viz-ggplot2.qmd
    - resources.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt



